name: Test

on:
  - push

jobs:
  test:
    runs-on: windows-2019
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.3', '3.2', '3.1', '3.0', '2.7']
    name: Ruby ${{ matrix.ruby-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
